"""Regenerate CONTENT.md — the checklist of every line she will read.

Cross-references src/maps.js (what exists in the world) against
data/memories.json (what you have actually written), so the list can never
drift from the game again. Run it after adding anything to a map:

    python tools/content_status.py            # rewrites CONTENT.md
    python tools/content_status.py --todo      # just prints what's left
"""
import json, os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
mem = json.load(open(os.path.join(ROOT, "data", "memories.json"), encoding="utf-8"))

TODO = "[TODO"


def load_maps():
    """Import src/maps.js with node and hand the real objects back. Parsing the
    file with regexes drifts the moment a building gains a nested `enter: {}`,
    and a checklist that quietly drops rows is worse than no checklist."""
    js = ("import { MAPS, STORY_POINTS } from %s;\n"
          "console.log(JSON.stringify({ MAPS, STORY_POINTS }));\n"
          % json.dumps(os.path.join(ROOT, "src", "maps.js")))
    with tempfile.NamedTemporaryFile("w", suffix=".mjs", delete=False) as f:
        f.write(js)
        path = f.name
    try:
        out = subprocess.run(["node", path], capture_output=True, text=True)
    except FileNotFoundError:
        sys.exit("this needs node on PATH (it imports src/maps.js directly)")
    finally:
        os.unlink(path)
    if out.returncode:
        sys.exit(out.stderr.strip() or "node failed to import src/maps.js")
    data = json.loads(out.stdout)
    return data["MAPS"], set(data["STORY_POINTS"])


def status(kind, key):
    """🟢 written / 🔴 TODO / 🟡 built-in (no entry in memories.json)"""
    entry = mem.get(kind, {}).get(key)
    if entry is None:
        return "🟡 built-in", False
    if TODO in json.dumps(entry, ensure_ascii=False):
        return "🔴 **TODO**", True
    return "🟢 written", False


rows_by_map, todo_ids = [], []
maps, story = load_maps()
# "required" means "on the ♥ list in maps.js" — see STORY_POINTS there. Every
# other spot is optional colour, which is not the same thing as unwritten.
for name, d in maps.items():
    title = d.get("name", name)
    interior = bool(d.get("interior"))
    rows = []
    for bd in d.get("buildings", []):
        if bd.get("point"):
            rows.append((bd["point"], "door", bd["point"] in story))
    for p in d.get("points", []):
        rows.append((p["id"], "spot", p["id"] in story))
    for n in d.get("npcs", []):
        if n.get("point"):
            rows.append((n["point"], "animal" if n.get("pet") else "person",
                         n["point"] in story))
        else:
            # background townsfolk: no memory, just chatter under npcs.<id>
            rows.append((n["id"], "townsfolk", False))
    if not rows:
        continue
    table = []
    for pid, kind, required in rows:
        st, is_todo = status("npcs" if kind == "townsfolk" else "points", pid)
        if is_todo:
            todo_ids.append((title, pid))
        table.append(f"| `{pid}` | {kind} | {'**yes**' if required else 'bonus'} | {st} |")
    rows_by_map.append((("🏠 " if interior else "🗺 ") + title, table))

# ---- the pieces that aren't tied to a place on a map
BIG = [
    ("meta.playerName", "her name — used everywhere, including the party banner"),
    ("meta.intro", "the three lines on arrival"),
    ("noah.greet_la", "how he introduces the whole game"),
    ("noah.chat", "small talk, cycles"),
    ("noah.after", "what he says once it's over"),
    ("mookie.lines", "the cat"),
    ("figs.all", "the payoff for every fig"),
    ("pumpkins.all", "the PUMPKINN!! payoff"),
    ("finale.prompt", "\"meet me at our apartment\""),
    ("finale.lines", "**THE REVEAL. the whole point of the game.**"),
    ("finale.title", "the card that comes up after"),
    ("party.surprise", "🎂 the party skit"),
    ("party.cake", "the candles"),
    ("party.after", "what's said once it's quiet"),
    ("credits.sub", "the dedication line"),
]
big_rows = []
for path, what in BIG:
    cur = mem
    for part in path.split("."):
        cur = (cur or {}).get(part) if isinstance(cur, dict) else None
    if cur is None:
        st = "🟡 built-in"
    elif TODO in json.dumps(cur, ensure_ascii=False):
        st = "🔴 **TODO**"
        todo_ids.append(("the big ones", path))
    else:
        st = "🟢 written"
    big_rows.append(f"| `{path}` | {what} | {st} |")

if "--todo" in sys.argv:
    for where, pid in todo_ids:
        print(f"{where:34} {pid}")
    print(f"\n{len(todo_ids)} left")
    sys.exit(0)

total = sum(len(t) for _, t in rows_by_map) + len(big_rows)
out = ["# ✍️ the content checklist", "",
       "*Generated by `python tools/content_status.py` — re-run it after adding",
       "anything to a map, and it will never drift from the game.*", "",
       "**Every word she reads lives in `data/memories.json`.** Anything you delete",
       "from that file falls back to the built-in copy in `src/world.js`, so the game",
       "never breaks — but the built-ins are mine, not yours.", "",
       "| status | means |", "|---|---|",
       "| 🟢 written | there is real copy in `memories.json` |",
       "| 🔴 **TODO** | still holds a `[TODO Noah: …]` placeholder |",
       "| 🟡 built-in | no entry in `memories.json` — the game is using my words |",
       "", "---", ""]
for title, table in rows_by_map:
    out += [f"## {title}", "",
            "| id | what | needed for the ending? | status |", "|---|---|---|---|"]
    out += table + [""]
out += ["## the big ones (not tied to a map)", "",
        "| where | what it is | status |", "|---|---|---|"] + big_rows + [""]
out += ["---", "",
        f"**{len(todo_ids)} of {total}** entries still need you. "
        "`python tools/content_status.py --todo` lists just those.", "",
        "## testing", "",
        "| how | what it does |", "|---|---|",
        "| *save `memories.json`* | the running game reloads it live — no refresh |",
        "| `?map=la_care_in&spawn=door` | jump straight to a room |",
        "| `?map=party` | jumps straight to the party + credits |",
        "| `?dev` then **ESC** | adds a **🎂 test the ending** button to the pause menu |",
        "| `?all` | marks everything found, so the finale triggers |",
        "| `?gate` | forces the password screen |",
        "| `?reset=1` | wipes the save (needed to re-run the finale) |", "",
        "## before you deploy", "",
        "- [ ] Clear every 🔴 above (`--todo` lists them)",
        "- [ ] Read the 🟡 rows and decide if my words are good enough",
        "- [ ] Write `finale.lines` — the reveal",
        "- [ ] Set the real password and re-encrypt "
        "(`python tools/crypt.py encrypt data/memories.json \"pw1,pw2\" \"hint\"`)",
        "- [ ] Play it start to finish (`?all` fast-checks the finale + party)", ""]

open(os.path.join(ROOT, "CONTENT.md"), "w", encoding="utf-8").write("\n".join(out))
print(f"wrote CONTENT.md — {len(todo_ids)} of {total} entries still need Noah")
